### ISSUE TITLE
Oncomplete.sh Uploads files to rclone remote before or after seeding?

### ISSUE THREAD

**Issue by nenokkadine** [xinxin8816/heroku-ariang-21vianet#24]

**Comment by xinxin8816** [comment]
After download completed

**Comment by nenokkadine** [comment]
ok  I will Try This then Thanks Dude
--on-bt-download-complete=<COMMAND>
For BitTorrent, a command specified in --on-download-complete is called after download completed and seeding is over. On the other hand, this option set the command to be executed after download completed but before seeding. See Event Hook for more details about COMMAND. Possible Values: /path/to/command

**Comment by xinxin8816** [comment]
I'm sorry, after reading the aria2c doc,i think you should add `on-bt-download-complete=./on-complete.sh` in aria2c.conf.

on-bt-download-complete=./on-complete.sh means uploading after download completed
on-download-complete=./on-complete.sh means uploading after download and seeding completed

I have never seeding by heroku because of it will reset every 24h.

**Comment by nenokkadine** [comment]
Yeah  Thanks.
I will Dockerize this Application as it is Getting Banned Instantly.thats why i am Asking you all these
